### ISSUE TITLE
글러벌 런칭

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1368]
- [ ] 다국어 지원 #613
- [ ] 세계날씨 지원 #1290 #1362
- [ ] 새로운 번역어 적용 #1366 
- [ ] Android Native 단위변경, 다국어, 세계날씨 지원 #1310 
- [ ] Push notification 다국어, 단위변경, 세계날씨 지원 #1308 
- [ ] Android 언어별 앱(+위젯) 스크린샷, 그래픽이미지, TV배너

- [ ] iOS Native 다국어 지원 #1332 
- [ ] iOS Native 세계날씨 지원 #1334
- [ ] iOS Native 단위변경 지원
- [ ] iOS 언어별 앱(+위젯) 스크린샷

- [ ] 세계 AQI 제공

**Comment by kimalec** [comment]
현재위치에 대한 source를 KMA로 해두고, 해외에 나간 경우 위치에 대한 데이터 오류가 발생함 -> "KMA에서는 현재위치에 대한 데이터를 제공하지 않습니다" 혹은 데이터 오류라고 표시 필요 (Widget, App 모두)

**Comment by kimalec** [comment]
Test Case (0.9.28)
* Android
- [ ] 앱 : 서울, 뉴욕, 도쿄, 북경, 베를린, 대만 날씨 확인
- [ ] 위젯 : 서울, 뉴욕 날씨 확인
- [ ] 앱 : 단위 변경 확인
- [ ] 위젯 : 단위 변경 동작 확인, 미세먼지 미동작 메세지 확인
- [ ] 앱 : 영어, 한국어, 일본어, 중국 간체, 중국 번체, 독일어
- [ ] 위젯 : 영어, 한국어, 일본어, 중국 간체, 중국 번체, 독일어

**Comment by kimalec** [comment]
0.9.28 문제점
한국어, 위젯 - 현재위치에 대한 지역명이 영어로 표시됨.
일본어, 앱 - 영어로 표시됨.
영어, 앱 - The day after tomorrow 02.15가 길어서 2줄로 표시됨.
디바이스가 새로 시작하거나, 위젯 변경이 있을때 아무것도 나오지 않아 에러로 보임 (위젯 기본값을 설정중으로 표기하게 하여 사용자에게 위젯 있음을 알릴필요가 있음.)
독일어, 위젯 - 해외 위젯 오류 발생
프랑스어, 위젯 - 해외 위젯 오류 발생

*  주의 {lang}.json 내 format이 잘못되면 해당언어는 나오지 않고, 기본언어로 표시됨.

**Comment by kimalec** [comment]
- [ ] 안드로이드 위젯 스크린샷을 언어별로 선택가능한지 확인.

**Comment by kimalec** [comment]
스토어 설명 영어 추가, 33개국 오픈
